export const enum TokenType {
  AND = 'AND',
  COMMA = 'COMMA',
  DIVIDE = 'DIVIDE',
  ELSE = 'ELSE',
  EQUAL = 'EQUAL',
  EQUAL_EQUAL = 'EQUAL_EQUAL',
  FALSE = 'FALSE',
  FOR = 'FOR',
  FUNCTION = 'FUNCTION',
  GT = 'GT',
  GT_EQUAL = 'GT_EQUAL',
  IDENTIFIER = 'IDENTIFIER',
  IF = 'IF',
  LEFT_BRACE = 'LEFT_BRACE',
  LEFT_PAREN = 'LEFT_PAREN',
  LT = 'LT',
  LT_EQUAL = 'LT_EQUAL',
  MINUS = 'MINUS',
  MULTIPLY = 'MULTIPLY',
  NIL = 'NIL',
  NOT = 'NOT',
  NOT_EQUAL = 'NOT_EQUAL',
  NUMBER = 'NUMBER',
  OR = 'OR',
  PLUS = 'PLUS',
  POWER = 'POWER',
  PRINT = 'PRINT',
  RETURN = 'RETURN',
  RIGHT_BRACE = 'RIGHT_BRACE',
  RIGHT_PAREN = 'RIGHT_PAREN',
  SEMICOLON = 'SEMICOLON',
  STRING = 'STRING',
  TRUE = 'TRUE',
  WHILE = 'WHILE',
  VAR = 'VAR',
}

export interface Token {
  type: TokenType;
  lexeme: string;
}
